modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]
modId="aae_mobs"
version="12.1.24.2"
displayName="AAE Mobs"
credits="Find the book."
displayURL="https://www.twitch.tv/engiegames"
logoFile="logo.png"
authors="EngieGames"
description="Made with MCreator"

[[dependencies.aae_mobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




